# Generated by Django 4.0.4 on 2022-05-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_peg_pegs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pegs',
            options={'verbose_name': 'PEG', 'verbose_name_plural': 'PEGS'},
        ),
    ]
