# Generated by Django 4.0.4 on 2022-05-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waifu',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
