# Generated by Django 4.0.4 on 2022-05-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_waifu_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waifu',
            options={'verbose_name': 'PEG', 'verbose_name_plural': 'PEGS'},
        ),
    ]
