# Generated by Django 4.0.4 on 2022-05-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_waifu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waifu',
            options={'verbose_name': 'Waifu', 'verbose_name_plural': 'Waifus'},
        ),
    ]
