# Generated by Django 4.0.4 on 2022-05-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_waifu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.RemoveField(
            model_name='waifu',
            name='rating',
        ),
        migrations.AlterField(
            model_name='waifu',
            name='waifu_pic',
            field=models.ImageField(upload_to='images/', verbose_name='Waifu pic'),
        ),
    ]
