# Generated by Django 4.0.4 on 2022-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comment_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waifu',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='waifu',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
