# Generated by Django 4.0.4 on 2022-05-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_waifu_rating_alter_waifu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waifu',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Rating'),
        ),
    ]
